-- Table Creation DDL .sql file

-- Authors: Jared Balakrishnan, Moiz Shaikh


-- DIM_VOLUNTEER_ICE TABLE

DROP TABLE IF EXISTS DIM_VOLUNTEER_ICE;

CREATE TABLE DIM_VOLUNTEER_ICE (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
    RECORD_ID VARCHAR(20) NOT NULL,
    EMERGENCY_CONTACT_NAME VARCHAR(255) NOT NULL,
    EMERGENCY_CONTACT_RELATIONSHIP VARCHAR(255),
    EMERGENCY_CONTACT_PHONE VARCHAR(255) DEFAULT NULL,
    EMERGENCY_CONTACT_EMAIL VARCHAR(255) DEFAULT NULL
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- DIM_VOLUNTEER_CONTACT TABLE

DROP TABLE IF EXISTS DIM_VOLUNTEER_CONTACT;

CREATE TABLE DIM_VOLUNTEER_CONTACT (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
    RECORD_ID VARCHAR(20) NOT NULL,
    VOLUNTEER_PHONE VARCHAR(255) DEFAULT NULL,
    VOLUNTEER_ALTERNATE_PHONE VARCHAR(255) DEFAULT NULL,
    VOLUNTEER_EMAIL VARCHAR(255) DEFAULT NULL,
    VOLUNTEER_ADDRESS_STREET VARCHAR(255) DEFAULT NULL,
    VOLUNTEER_ADDRESS_CITY VARCHAR(255) DEFAULT NULL,
    VOLUNTEER_ADDRESS_PROVINCE VARCHAR(255) DEFAULT NULL,
    VOLUNTEER_ADDRESS_COUNTRY VARCHAR(255) DEFAULT NULL
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- DIM_VOLUNTEER_FORM TABLE

DROP TABLE IF EXISTS DIM_VOLUNTEER_FORM;

CREATE TABLE DIM_VOLUNTEER_FORM (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RECORD_ID VARCHAR(20) NOT NULL,
    FORM_CREATED_DATE DATETIME NOT NULL,
    FORM_ID VARCHAR(255) DEFAULT NULL,
    FORM_URL VARCHAR(1500) DEFAULT NULL
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- DIM_VOLUNTEER_DELIVERY_PREFERENCES TABLE

DROP TABLE IF EXISTS DIM_VOLUNTEER_DELIVERY_PREFERENCES;

CREATE TABLE DIM_VOLUNTEER_DELIVERY_PREFERENCES (
     ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
     RECORD_ID VARCHAR(25) NOT NULL,
     VOL_FIRST_NAME VARCHAR(255) NOT NULL,
     VOL_LAST_NAME VARCHAR(255) DEFAULT NULL,
     DEL_HAVE_A_CAR TINYINT(1),
     DEL_BY_BIKE TINYINT(1),
     DEL_AGE_GEQ_25 TINYINT(1),
     DEL_ACCOUNT_COMMUNAUTO TINYINT(1),
     DEL_IN_PAIRS TINYINT(1),
     DEL_BY_PUBLIC_TRANSIT TINYINT(1),
     DEL_LICENSED_TO_DRIVE TINYINT(1),
     DEL_ACCOUNT_TURO TINYINT(1)
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- DIM_VOLUNTEER_PROGRAM_PREFERENCES TABLE

DROP TABLE IF EXISTS DIM_VOLUNTEER_PROGRAM_PREFERENCES;

CREATE TABLE DIM_VOLUNTEER_PROGRAM_PREFERENCES (
     ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
     RECORD_ID VARCHAR(25) NOT NULL,
     VOL_FIRST_NAME VARCHAR(255) NOT NULL,
     VOL_LAST_NAME VARCHAR(255) DEFAULT NULL,
     PGM_DELIVERY TINYINT(1),
     PGM_KITCHEN TINYINT(1),
     PGM_URBAN_AGRICULTURE TINYINT(1),
     PGM_FARM TINYINT(1),
     PGM_CARING_CALLS TINYINT(1),
     PGM_VEGGIE_BASKETS TINYINT(1),
     PGM_EVENTS TINYINT(1),
     PGM_COLLECTIVES TINYINT(1)
) DEFAULT  CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- DIM_VOLUNTEER_SKILLS TABLE

DROP TABLE IF EXISTS DIM_VOLUNTEER_SKILLS;

CREATE TABLE DIM_VOLUNTEER_SKILLS (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RECORD_ID VARCHAR(25) NOT NULL,
    VOL_FIRST_NAME VARCHAR(255) NOT NULL,
    VOL_LAST_NAME VARCHAR(255) DEFAULT NULL,
    SKILLS_DATA_ENTRY TINYINT(1),
    SKILLS_TRANSLATION TINYINT(1),
    SKILLS_PHOTOGRAPHY TINYINT(1),
    SKILLS_OTHER TINYINT(1),
    SKILLS_GRAPHIC_DESIGN TINYINT(1),
    SKILLS_FUNDRAISING TINYINT(1),
    SKILLS_EVENTS TINYINT(1)
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- DIM_VOLUNTEER_DELIVERY_SHIFT_AVAILABILITY TABLE


DROP TABLE IF EXISTS DIM_VOLUNTEER_DELIVERY_SHIFT_AVAILABILITY;

CREATE TABLE DIM_VOLUNTEER_DELIVERY_SHIFT_AVAILABILITY (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RECORD_ID VARCHAR(25) NOT NULL,
    VOL_FIRST_NAME VARCHAR(255) NOT NULL,
    VOL_LAST_NAME VARCHAR(255) DEFAULT NULL,
    DEL_SHIFT_MONDAY TINYINT(1),
    DEL_SHIFT_TUESDAY TINYINT(1),
    DEL_SHIFT_WEDNESDAY TINYINT(1),
    DEL_SHIFT_FRIDAY TINYINT(1),
    DEL_SHIFT_SATURDAY TINYINT(1)
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- DIM_VOLUNTEER_KITCHEN_SHIFT_AVAILABILITY TABLE


DROP TABLE IF EXISTS DIM_VOLUNTEER_KITCHEN_SHIFT_AVAILABILITY;

CREATE TABLE DIM_VOLUNTEER_KITCHEN_SHIFT_AVAILABILITY (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RECORD_ID VARCHAR(25) NOT NULL,
    VOL_FIRST_NAME VARCHAR(255) NOT NULL,
    VOL_LAST_NAME VARCHAR(255) DEFAULT NULL,
    KITCHEN_MONDAY_AM TINYINT(1),
    KITCHEN_MONDAY_PM TINYINT(1),
    KITCHEN_TUESDAY_AM TINYINT(1),
    KITCHEN_WEDNESDAY_AM TINYINT(1),
    KITCHEN_FRIDAY_AM TINYINT(1),
    KITCHEN_TUESDAY_PM TINYINT(1),
    KITCHEN_WEDNESDAY_PM TINYINT(1),
    KITCHEN_THURSDAY_PM TINYINT(1),
    KITCHEN_FRIDAY_PM TINYINT(1),
    KITCHEN_SATURDAY_AM TINYINT(1),
    KITCHEN_SATURDAY_PM TINYINT(1)
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
