-- Table Creation DDL .sql file

-- Authors: Jared Balakrishnan, Moiz Shaikh


DROP TABLE IF EXISTS FACT_VOLUNTEER_CENTRAL;

CREATE TABLE FACT_VOLUNTEER_CENTRAL (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RECORD_ID VARCHAR(25) NOT NULL,
    VOL_STATUS VARCHAR(255),
    LAST_MODIFIED VARCHAR(255),
    VOL_APP_ACCOUNT_ID VARCHAR(255),
    VOL_FIRST_NAME VARCHAR(255) NOT NULL,
    VOL_LAST_NAME VARCHAR(255) DEFAULT NULL,
    VOL_DATE_OF_BIRTH DATE DEFAULT NULL,
    VOL_AGE INTEGER DEFAULT NULL,
    VOL_CREATED DATE,
    VOL_ORIGINAL_DATE_CREATED DATE,
    VOL_WELCOME_SESSION_DATE DATE,
    VOL_WELCOME_SESSION_STATUS VARCHAR(255),
    VOL_WELCOME_SESSION_LOCATION VARCHAR(255),
    VOL_PREFERRED_PRONOUNS VARCHAR(255),
    VOL_PRIMARY_LANGUAGE VARCHAR(60),
    VOL_CALL_LIST_FLAG VARCHAR(25),
    VOL_LAST_MINUTE_FLAG VARCHAR(25),
    VOL_LAST_SPOKEN_DATE DATE,
    VOL_LEFT_MESSAGE_DATE DATE,
    VOL_LIVE_CLOSE_FLAG VARCHAR(25),
    VOL_SPECIAL_NEEDS_FLAG VARCHAR(25),
    VOL_EMAIL_ADDRESS VARCHAR(255),
    VOL_COVID_CONSENT_FLAG VARCHAR(60),
    VOL_PROGRAMS VARCHAR(500),
    VOL_PROGRAMS_GROUP VARCHAR(500),
    VOL_SKILLS_MAIN VARCHAR(500),
    VOL_SKILLS_OTHERS TEXT,
    VOL_SPECIAL_NEEDS TEXT,
    VOL_TAGS VARCHAR(500),
    VOL_DAYS_AVAIL_OLD VARCHAR(255),
    VOL_DELIVERIES_PREFERENCE VARCHAR(500),
    VOL_DELIVERY_AVAIL VARCHAR(500),
    VOL_KITCHEN_AVAIL VARCHAR(500),
    VOL_PHOTO_CONSENT_STATUS VARCHAR(255),
    VOL_KITCHEN_EXPERIENCE VARCHAR(255),
    VOL_SCHOOL_HOURS_FLAG VARCHAR(255),
    VOL_COMMUNITY_PAID_FLAG VARCHAR(255),
    VOL_HOURS_DATES VARCHAR(500),
    VOL_DATA_SOURCE VARCHAR(255),
    VOL_WELCOME_SESSION_STAFF_NAME VARCHAR(255),
    VOL_WELCOME_SESSION_STAFF_ID VARCHAR(255),
    VOL_WELCOME_SESSION_STAFF_EMAIL VARCHAR(255)
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
